# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: devpulse

before:
  hooks:
    - go mod tidy

builds:
  - id: devpulse
    binary: devpulse
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Nishanth1812/devpulse/cmd.version={{ .Version }}
      - -X github.com/Nishanth1812/devpulse/cmd.commit={{ .Commit }}
      - -X github.com/Nishanth1812/devpulse/cmd.buildDate={{ .Date }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

universal_binaries:
  - replace: true

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README.md
      - SECURITY.md
      - CONTRIBUTING.md
      - CODE_OF_CONDUCT.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).