# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: devpulse

before:
  hooks:
    - go mod tidy

builds:
  - id: devpulse
    binary: devpulse
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/Nishanth1812/devpulse/cmd.version={{ .Version }}
      - -X github.com/Nishanth1812/devpulse/cmd.commit={{ .Commit }}
      - -X github.com/Nishanth1812/devpulse/cmd.buildDate={{ .Date }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
      - "386"

universal_binaries:
  - replace: true

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE*
      - README.md
      - SECURITY.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: git
  sort: asc
  groups:
    - title: "Features"
      regexp: "^.*feat[(\\w)]*:.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:.*$"
      order: 10
    - title: "Security"
      regexp: "^.*security[(\\w)]*:.*$"
      order: 20
    - title: "Performance"
      regexp: "^.*perf[(\\w)]*:.*$"
      order: 30
    - title: "Refactors"
      regexp: "^.*refactor[(\\w)]*:.*$"
      order: 40
    - title: "CI & build"
      regexp: "^.*(ci|build)[(\\w)]*:.*$"
      order: 50
    - title: "Chores"
      regexp: "^.*chore[(\\w)]*:.*$"
      order: 60
    - title: "Other changes"
      order: 999
  filters:
    exclude:
      - "^Merge pull request"
      - "^Merge branch"

release:
  header: |-
    ## What's Changed

    View the full diff on [GitHub](https://github.com/Nishanth1812/DevPulse/compare/{{ .PreviousTag }}...{{ .Tag }}).

  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).